"""Reproduction-vs-claimed table (Paper / Model / Link / Dataset / Code-available
/ per-paper metrics), in LaTeX. Same three rows and protocols as
eval_paper_metrics.py (C-Tran ML_F1/Bin_AUC/Bin_F1, RetExpert F1/Kappa,
RIADD MD Avg/SC2 F1/Specificity) -- see that script's docstring for exactly
how each metric is defined and reproduced.

RetExpert's numbers are PLACEHOLDERS: its checkpoints are mid-retrain (the
FDCM-loss and SOA-block-sampling bug fixes from RetExpert/losses/retexpert_loss.py
and RetExpert/utils/engine.py), so `retexpert_mured_seed*.npz` still reflects the
pre-fix model. Re-run this script once the 5 fixed-loss seeds finish and are
dumped to get real numbers in their place.

Writes tables/reproduction_table.tex.
"""
import os
import sys

import numpy as np
from scipy import stats
from sklearn.metrics import average_precision_score, roc_auc_score

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), 'C-Tran'))
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), 'Pytorch-RIADD'))
from utils.mured_metrics import compute_mured_metrics
from metrics9 import tune_thresholds

PROBS = os.environ['PROBS_DIR']
SEEDS = (42, 43, 44, 45, 46)
HERE = os.path.dirname(os.path.abspath(__file__))

PLACEHOLDER = 'TBD'   # RetExpert reproduction cells -- fixed-loss retrain in flight


def ci95(vals):
    v = np.asarray(vals, float)
    return v.mean(), stats.t.ppf(0.975, len(v) - 1) * v.std(ddof=1) / np.sqrt(len(v))


def macro(fn, p, t):
    return float(np.mean([fn(t[:, c], p[:, c]) for c in range(t.shape[1])
                          if len(np.unique(t[:, c])) > 1]))


def fmt(mean, half, pct=True):
    m = mean * 100 if pct else mean
    return f"{m:.2f}\\%" if half is None else f"{m:.2f}\\%\\,[{(mean-half)*100:.2f}, {(mean+half)*100:.2f}]"


# --- C-Tran: paper's own ML_F1 / Bin_AUC / Bin_F1 protocol ------------------
ct = {'ML_F1': [], 'Bin_AUC': [], 'Bin_F1': []}
for s in SEEDS:
    z = np.load(f'{PROBS}/ctran_mured_seed{s}.npz', allow_pickle=True)
    cols = [str(c) for c in z['label_cols']]
    m = compute_mured_metrics(z['test_true'], z['test_pred'], cols)
    for k in ct:
        ct[k].append(m[k])

# --- RIADD/KAMATALAB: paper's own MD Avg / SC2 F1 / Specificity ------------
rd = {'MD Avg': [], 'SC2 F1': [], 'Specificity': []}
for s in SEEDS:
    te = np.load(f'{PROBS}/riadd3_blend_test_seed{s}.npz')
    va = np.load(f'{PROBS}/riadd3_blend_val_seed{s}.npz')
    p, t = te['probs'], te['targets']
    thr = tune_thresholds(va['probs'], va['targets'])
    pred = (p[:, 1:] >= thr[None, 1:]).astype(int)
    y = t[:, 1:].astype(int)
    md = 0.5 * (macro(roc_auc_score, p[:, 1:], t[:, 1:])
                + macro(average_precision_score, p[:, 1:], t[:, 1:]))
    f1s, specs = [], []
    for c in range(y.shape[1]):
        tp = int(((pred[:, c] == 1) & (y[:, c] == 1)).sum())
        fp = int(((pred[:, c] == 1) & (y[:, c] == 0)).sum())
        fn = int(((pred[:, c] == 0) & (y[:, c] == 1)).sum())
        tn = int(((pred[:, c] == 0) & (y[:, c] == 0)).sum())
        f1s.append((2 * tp / (2 * tp + fp + fn)) if (2 * tp + fp + fn) > 0 else 0.0)
        specs.append((tn / (tn + fp)) if (tn + fp) > 0 else 0.0)
    rd['MD Avg'].append(md)
    rd['SC2 F1'].append(float(np.mean(f1s)))
    rd['Specificity'].append(float(np.mean(specs)))

ct_cells = {k: ci95(v) for k, v in ct.items()}
rd_cells = {k: ci95(v) for k, v in rd.items()}

ROWS = [
    dict(paper="Multi-Label Retinal Disease Classification Using Transformers",
         model="C-Tran", link="https://github.com/QData/C-Tran", dataset="MuReD",
         code="NO",
         metrics=[("ML\\_F1", fmt(*ct_cells['ML_F1']), "57.30\\%"),
                  ("Bin\\_AUC", fmt(*ct_cells['Bin_AUC']), "97.60\\%"),
                  ("Bin\\_F1", fmt(*ct_cells['Bin_F1']), "82.40\\%")]),
    dict(paper="A test-time clinically adaptive framework for detecting multiple "
               "fundus diseases by harnessing ophthalmic foundation models",
         model="RetExpert", link="https://github.com/OVS-AILab/RetExpert", dataset="MuReD",
         code="YES",
         metrics=[("F1", PLACEHOLDER, "73.01\\%"),
                  ("Kappa", PLACEHOLDER, "70.84\\%")]),
    dict(paper="RFMiD: Retinal Image Analysis for multi-Disease Detection challenge",
         model="RIADD (KAMATALAB)", link="https://github.com/Hanson0910/Pytorch-RIADD",
         dataset="RFMiD", code="YES",
         metrics=[("Multi-Disease Avg", fmt(*rd_cells['MD Avg']), "78.21\\%"),
                  ("F1", fmt(*rd_cells['SC2 F1']), "55.46\\%"),
                  ("Specificity", fmt(*rd_cells['Specificity']), "99.57\\%")]),
]

N = max(len(r['metrics']) for r in ROWS)  # widest row -> fixed column count
col_spec = "llllc" + "cc" * N

lines = []
lines.append("% Generated by make_reproduction_table.py -- mean [95% CI] over seeds 42-46")
lines.append("% RetExpert cells are PLACEHOLDERS pending the fixed-loss retrain (see script docstring)")
lines.append("% Requires \\usepackage{booktabs} and \\usepackage{hyperref}")
lines.append("\\begin{table*}[t]")
lines.append("\\centering")
lines.append("\\caption{Reproduction vs.\\ claimed, on each paper's own reported metrics "
             "(mean [95\\% CI] over 5 seeds; single-value cells are point estimates from a "
             "threshold-free or single-model protocol). RetExpert cells marked TBD are "
             "pending a retrain after fixing two implementation bugs found against the "
             "paper's own Eqs.\\ 2--3 and 5 (SOA block sampling, FDCM loss).}")
lines.append("\\label{tab:reproduction}")
lines.append(f"\\begin{{tabular}}{{{col_spec}}}")
lines.append("\\toprule")

for i, r in enumerate(ROWS):
    if i > 0:
        lines.append("\\midrule")
    nm = len(r['metrics'])
    grp_header = " & ".join(f"\\multicolumn{{2}}{{c}}{{{name}}}" for name, _, _ in r['metrics'])
    grp_header += "".join(" & \\multicolumn{2}{c}{}" for _ in range(N - nm))
    lines.append(f" & & & & & {grp_header} \\\\")

    cmids = []
    col = 6
    for _ in r['metrics']:
        cmids.append(f"\\cmidrule(lr){{{col}-{col+1}}}")
        col += 2
    lines.append(" ".join(cmids))

    subhdr = " & ".join("Reproduction & Claimed" for _ in r['metrics'])
    subhdr += "".join(" & &" for _ in range(N - nm))
    lines.append(f" & & & & & {subhdr} \\\\")

    lines.append("\\midrule")
    data = " & ".join(f"{repro} & {claim}" for _, repro, claim in r['metrics'])
    data += "".join(" & &" for _ in range(N - nm))
    paper_cell = r['paper'].replace('&', '\\&')
    lines.append(f"{paper_cell} & {r['model']} & \\href{{{r['link']}}}{{link}} & "
                 f"{r['dataset']} & {r['code']} & {data} \\\\")

lines.append("\\bottomrule")
lines.append("\\end{tabular}")
lines.append("\\end{table*}")

out = os.path.join(HERE, 'tables', 'reproduction_table.tex')
os.makedirs(os.path.dirname(out), exist_ok=True)
with open(out, 'w') as f:
    f.write("\n".join(lines) + "\n")
print(f"wrote {out}")
print()
print("\n".join(lines))
